export default [
  {
    component: 'Layout',
    icon: "icon-quanxianguanli",
    id: 6000,
    keepAlive: "0",
    label: "OrderManage",
    name: "OrderManage",
    parentId: -1,
    path: "/hotel",
    redirect: null,
    sort: 0,
    spread: false,
    type: "0",
    children: [
     //  {
     //   authority: null,
     //   children: [],
     //   code: null,
     //   component: "views/hotel/available/index",
     //   icon: "icon-yonghuguanli",
     //   id: 6001,
     //   keepAlive: "0",
     //   label: "可用房型",
     //   name: "可用房型",
     //   parentId: 6000,
     //   path: "available",
     //   redirect: null,
     //   sort: 5,
     //   spread: false,
     // type: "0",
    //},
      {
        authority: null,
        children: [],
        code: null,
        component: "views/hotel/order/index",
        icon: "icon-yonghuguanli",
        id: 6002,
        keepAlive: "0",
        label: "ItinerarySearch",
        name: "ItinerarySearch",
        parentId: 6000,
        path: "order",
        redirect: null,
        sort: 6,
        spread: false,
        type: "0",
      }
      ,
     //{
     //   authority: null,
     //   children: [],
     //   code: null,
     //   component: "views/hotel/introduction/index",
     //   icon: "icon-yonghuguanli",
     //   id: 6003,
     //   keepAlive: "0",
     //   label: "酒店信息",
    //  name: "酒店信息",
     //    parentId: 6000,
     //   path: "introduction",
     //   redirect: null,
     //   sort: 7,
     //   spread: false,
     //   type: "0",
      //}
    ]
  },{
    component: 'Layout',
    icon: "icon-quanxianguanli",
    id: 2000,
    keepAlive: "0",
    label: "SupplyChain",
    name: "SupplyChain",
    parentId: -1,
    path: "/supply",
    redirect: null,
    sort: 0,
    spread: false,
    type: "0",
    children: [
      {
        authority: null,
        children: [],
        code: null,
        component: "views/supplierChain/supplierManager",
        icon: "icon-yonghuguanli",
        id: 2001,
        keepAlive: "0",
        label: "SupplierManager",
        name: "SupplierManager",
        parentId: 2000,
        path: "supplierbaseinfo",
        redirect: null,
        sort: 5,
        spread: false,
        type: "0",
      }
    ]
  },{
    component: 'Layout',
    icon: "icon-quanxianguanli",
    id: 3000,
    keepAlive: "0",
    label: "System Monitor",
    name: "System Monitor",
    parentId: -1,
    path: "/monitoring",
    redirect: null,
    sort: 0,
    spread: false,
    type: "0",
    children: [
      {
        authority: null,
        children: [],
        code: null,
        component: null,
        icon: "icon-yonghuguanli",
        id: 3001,
        keepAlive: "0",
        label: "Registry Center",
        name: "Registry Center",
        parentId: 3000,
        path: "http://47.244.21.45:8765",
        redirect: null,
        sort: 5,
        spread: false,
        type: "0"
      },
      {
        authority: null,
        children: [],
        code: null,
        component: null,
        icon: "icon-yonghuguanli",
        id: 3001,
        keepAlive: "0",
        label: "ApiOverview",
        name: "ApiOverview",
        parentId: 3000,
        path: "http://47.244.21.45:7430/swagger-ui.html",
        redirect: null,
        sort: 5,
        spread: false,
        type: "0"
      }
    ]
  },{
    component: 'Layout',
    icon: "icon-quanxianguanli",
    id: 4000,
    keepAlive: "0",
    label: "SupplierDataAnalysis",
    name: "SupplierDataAnalysis",
    parentId: -1,
    path: "/chart",
    redirect: null,
    sort: 0,
    spread: false,
    type: "0",
    children: [
      {
        authority: null,
        children: [],
        code: null,
        component: 'views/chart/worldMap',
        icon: "icon-yonghuguanli",
        id: 4001,
        keepAlive: "0",
        label: "GlobalHotelDistribution",
        name: "GlobalHotelDistribution",
        parentId: 4000,
        path: "worldMap",
        redirect: null,
        sort: 5,
        spread: false,
        type: "0"
      },{
        authority: null,
        children: [],
        code: null,
        component: 'views/chart/barGraph',
        icon: "icon-yonghuguanli",
        id: 4002,
        keepAlive: "0",
        label: "QuantityOfHotelTop10",
        name: "QuantityOfHotelTop10",
        parentId: 4000,
        path: "barGraph",
        redirect: null,
        sort: 5,
        spread: false,
        type: "0"
      },{
        authority: null,
        children: [],
        code: null,
        component: 'views/chart/scrollGraph',
        icon: "icon-yonghuguanli",
        id: 4003,
        keepAlive: "0",
        label: "QuantityOfHotel'Pictures",
        name: "QuantityOfHotel'Pictures",
        parentId: 4000,
        path: "scrollGraph",
        redirect: null,
        sort: 5,
        spread: false,
        type: "0"
      }
    ]
  },
  {
    component: 'Layout',
    icon: "icon-quanxianguanli",
    id: 5000,
    keepAlive: "0",
    label: "HotelResources",
    name: "HotelResources",
    parentId: -1,
    path: "/hotelresources",
    redirect: null,
    sort: 0,
    spread: false,
    type: "0",
    children: [
      {
        authority: null,
        children: [],
        code: null,
        component: "views/HotelResources/SupplierHotelResources",
        icon: "icon-yonghuguanli",
        id: 5001,
        keepAlive: "0",
        label: "SupplierHotelResources",
        name: "SupplierHotelResources",
        parentId: 5000,
        path: "supplierbaseinfo",
        redirect: null,
        sort: 5,
        spread: false,
        type: "0",
      }
    ]
  }
]